# Generated by Django 5.1.6 on 2025-06-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(choices=[('DR', 'Dr.'), ('PROF_DR', 'Prof. Dr.'), ('DR_RER_NAT', 'Dr. rer. nat.')], default='DR', max_length=50, verbose_name='Titel')),
                ('specialty', models.CharField(choices=[('ALLGEMEIN', 'Allgemeinmedizin'), ('RADIOLOGIE', 'Radiologie'), ('HAUT', 'Hautarzt'), ('KARDIO', 'Kardiologie'), ('NEURO', 'Neurologie'), ('PAEDIA', 'Pädiatrie'), ('UROLOGIE', 'Urologie')], default='ALLGEMEIN', max_length=100, verbose_name='Spezialität')),
            ],
            options={
                'verbose_name': 'Arzt',
                'verbose_name_plural': 'Ärzte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name des Patienten')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patienten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel des Termins')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('date', models.DateField(verbose_name='Datum des Termins')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking_app.doctor', verbose_name='Arzt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking_app.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['date', 'title'],
            },
        ),
    ]
